language:
  - cpp
compiler:
  - g++
  - clang++
before_install:
  - sudo apt-get install libboost-dev
  - wget https://github.com/headmyshoulder/odeint-v2/archive/v2.2.tar.gz
  - tar xvzf v2.2.tar.gz
  - sudo cp -r odeint-v2-2.2/boost/numeric/odeint/ /usr/include/boost/numeric/odeint
  - sudo cp odeint-v2-2.2/boost/numeric/odeint.hpp /usr/include/boost/numeric/odeint.hpp
script:
  - $CXX two_level.cpp -o two_level
  - ./two_level
